version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: ./tour_app_go
    container_name: "tour_app_go"
    tty: true
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - ./tour_app_go/app:/go/src/app